In [1]:
import pandas as pd

In [2]:
# Load structured dataset

df = pd.read_csv("../datasets/HDFS_2k_structured.csv")

df.head()

,Date,Time,Thread_ID,Level,Component,Message
0,81109,203615,148,INFO,dfs.DataNode$PacketResponder:,PacketResponder 1 for block blk_38865049064139...
1,81109,203807,222,INFO,dfs.DataNode$PacketResponder:,PacketResponder 0 for block blk_-6952295868487...
2,81109,204005,35,INFO,dfs.FSNamesystem:,BLOCK* NameSystem.addStoredBlock: blockMap upd...
3,81109,204015,308,INFO,dfs.DataNode$PacketResponder:,PacketResponder 2 for block blk_82291938032499...
4,81109,204106,329,INFO,dfs.DataNode$PacketResponder:,PacketResponder 2 for block blk_-6670958622368...

In [3]:
# Feature Engineering

df["Message_Length"] = df["Message"].str.len()

df["Has_Block_ID"] = df["Message"].str.contains(
    "blk_", regex=False
).astype(int)

df["Has_PacketResponder"] = df["Message"].str.contains(
    "PacketResponder",
    case=False
).astype(int)

df["Has_Error"] = df["Message"].str.contains(
    "error",
    case=False,
    na=False
).astype(int)

df["Is_WARN"] = (df["Level"] == "WARN").astype(int)

df.head()

,Date,Time,Thread_ID,Level,Component,Message,Message_Length,Has_Block_ID,Has_PacketResponder,Has_Error,Is_WARN
0,81109,203615,148,INFO,dfs.DataNode$PacketResponder:,PacketResponder 1 for block blk_38865049064139...,61,1,1,0,0
1,81109,203807,222,INFO,dfs.DataNode$PacketResponder:,PacketResponder 0 for block blk_-6952295868487...,64,1,1,0,0
2,81109,204005,35,INFO,dfs.FSNamesystem:,BLOCK* NameSystem.addStoredBlock: blockMap upd...,121,1,0,0,0
3,81109,204015,308,INFO,dfs.DataNode$PacketResponder:,PacketResponder 2 for block blk_82291938032499...,63,1,1,0,0
4,81109,204106,329,INFO,dfs.DataNode$PacketResponder:,PacketResponder 2 for block blk_-6670958622368...,64,1,1,0,0

In [4]:
# Selecting features for machine learning

features = [
    "Message_Length",
    "Has_Block_ID",
    "Has_PacketResponder",
    "Has_Error",
    "Is_WARN"
]

X = df[features]

X.head()

   Message_Length  Has_Block_ID  Has_PacketResponder  Has_Error  Is_WARN
0              61             1                    1          0        0
1              64             1                    1          0        0
2             121             1                    0          0        0
3              63             1                    1          0        0
4              64             1                    1          0        0

## Observation: Machine Learning Feature Matrix

A feature matrix named **X** was created by selecting the engineered numerical and binary features.

The feature matrix excludes raw textual information and retains only machine-learning-ready variables.

This matrix will serve as the input for anomaly detection algorithms in the subsequent experiments.

In [5]:
print("Feature Matrix Shape:", X.shape)

Feature Matrix Shape: (2000, 5)